const ATTRS=[
  ['three','三分'],['mid','中投'],['finish','终结'],['pass','传球'],['handle','控球'],['speed','速度'],['vertical','弹跳'],['strength','力量'],['rebound','篮板'],['steal','抢断'],['block','盖帽'],['perDef','外防'],['durability','耐久']
];
const POS={
 PG:{name:'控球后卫',icon:'🎯',desc:'组织、控球、速度权重最高',weights:{pass:.17,handle:.17,speed:.11,three:.10,mid:.08,finish:.08,steal:.08,perDef:.08,durability:.05,vertical:.02,strength:.02,rebound:.01,block:.03}},
 SG:{name:'得分后卫',icon:'🔥',desc:'外线得分、终结与外防',weights:{three:.15,mid:.13,finish:.13,handle:.10,speed:.09,perDef:.09,steal:.07,pass:.06,durability:.05,vertical:.05,strength:.03,rebound:.02,block:.03}},
 SF:{name:'小前锋',icon:'🏃',desc:'最均衡的攻防一体模板',weights:{finish:.11,three:.10,mid:.09,handle:.08,pass:.08,speed:.09,vertical:.07,strength:.07,rebound:.07,steal:.06,block:.05,perDef:.08,durability:.05}},
 PF:{name:'大前锋',icon:'💪',desc:'力量、篮板、护框兼顾空间',weights:{strength:.13,rebound:.13,block:.11,finish:.11,vertical:.09,perDef:.07,mid:.07,three:.07,durability:.07,speed:.05,pass:.04,handle:.02,steal:.04}},
 C:{name:'中锋',icon:'🧱',desc:'篮板、护框、力量与篮下终结',weights:{rebound:.17,block:.16,strength:.14,finish:.13,vertical:.09,durability:.08,perDef:.06,pass:.04,speed:.04,mid:.03,three:.02,handle:.01,steal:.03}}
};
const NAMES=['陆沉','周野','程澈','沈川','顾行','林启','江屿','许峥','季临','韩彻','宋驰','白砚','严骁','秦曜','凌峰','唐锐','洛川','苏衡','楚越','叶航','段星','贺燃','商陆','傅野','夏川','陈竞','温朔','霍远','梁策','纪辰'];
const TEAMS=[
 ['海湾鲨鱼','🌊'],['北境狼队','🐺'],['霓虹闪电','⚡'],['金州猎鹰','🦅'],['钢城巨人','🏗️'],['沙漠响尾蛇','🐍'],['首都骑士','🛡️'],['港城浪潮','🌊'],['红杉先锋','🌲'],['湖畔王冠','👑'],['风城幽灵','👻'],['星城彗星','☄️'],['雪原猛犸','🦣'],['山城火炬','🔥'],['河谷野牛','🐃'],['东岸灯塔','🗼'],['西岭飓风','🌪️'],['银湾水手','⚓'],['太阳城烈焰','☀️'],['森林游侠','🏹'],['黑曜石军团','⬛'],['蓝港海盗','🏴‍☠️'],['高原雷霆','🌩️'],['南湾虎鲸','🐋'],['云城飞马','🪽'],['峡谷公牛','🐂'],['极光冰刃','🧊'],['自由城火箭','🚀'],['皇家雄狮','🦁'],['曙光凤凰','🐦‍🔥']
];
const SAVE='basketball_legend_v1';
let state={screen:'home',position:null,attrs:{},sources:{},locked:0,rerolls:4,currentCandidates:[],ovr:0,team:null,pick:null,age:19,season:1,games:0,wins:0,losses:0,seasonStats:{pts:0,reb:0,ast:0,stl:0,blk:0},history:[],awards:[],growth:62,health:92,morale:78,legacy:0,potential:88,contract:null,contractOffers:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(SAVE,JSON.stringify(state))}
function load(){try{const x=JSON.parse(localStorage.getItem(SAVE));if(x){state=x;ensureState()}}catch(e){}}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');state.screen=id;save();window.scrollTo({top:0,behavior:'smooth'})}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function rnd(a,b){return Math.floor(Math.random()*(b-a+1))+a}function clamp(x,a,b){return Math.max(a,Math.min(b,x))}
function money(v){return `$${Number(v||0).toFixed(1)}M`}
function rookieBaseSalary(pick){if(pick===1)return 13.6;if(pick<=3)return 11.8;if(pick<=5)return 9.7;if(pick<=10)return 7.2;if(pick<=20)return 4.5;return 2.8}
function buildContract(team,type,startSalary,length,year=1){const annual=[];for(let i=0;i<length;i++)annual.push(Number((startSalary*Math.pow(1.05,i)).toFixed(1)));return{team,type,length,year,annual,total:Number(annual.reduce((a,b)=>a+b,0).toFixed(1))}}
function makeRookieContract(){const base=rookieBaseSalary(state.pick||30);return buildContract(state.team?.[0]||'未知球队','新秀合同',base,4,1)}
function currentSalary(){if(!state.contract)return 0;return state.contract.annual[Math.max(0,Math.min(state.contract.year-1,state.contract.annual.length-1))]||0}
function ensureState(){state.history=state.history||[];state.awards=state.awards||[];state.lastGames=state.lastGames||[];state.seasonStats=state.seasonStats||{pts:0,reb:0,ast:0,stl:0,blk:0};if(state.team&&!state.contract){if((state.season||1)<=4){state.contract=makeRookieContract();state.contract.year=Math.max(1,Math.min(state.season||1,4))}else{state.contract=buildContract(state.team[0],'老将合同',Math.max(8,(state.ovr-70)*1.15),3,1)}}}
function salaryMarketValue(){const last=state.history[state.history.length-1];const pts=last?.avg?.pts||baseAverages().pts;const awardBoost=(last?.awards||[]).reduce((n,a)=>n+(a==='MVP'?7:a==='总冠军'?4:a==='FMVP'?5:a.includes('最佳阵容')?3:a==='全明星'?1.5:0),0);const agePenalty=state.age>=33?(state.age-32)*2.0:0;return clamp(2.5+(state.ovr-68)*1.28+pts*.28+state.legacy*.08+awardBoost-agePenalty,2.5,62)}
function generateContractOffers(){const market=salaryMarketValue();const current=state.team[0];const pool=TEAMS.filter(t=>t[0]!==current).sort(()=>Math.random()-.5);const teams=[state.team,pool[0],pool[1]];return teams.map((t,i)=>{const maxYears=state.age>=34?2:state.age>=31?3:5;const years=i===0?clamp(rnd(2,maxYears),1,5):rnd(1,maxYears);const mult=i===0?(0.94+Math.random()*.08):(0.88+Math.random()*.20);const salary=clamp(Number((market*mult).toFixed(1)),2.2,65);return{team:t,type:state.age<=28?'顶薪竞争合同':'自由球员合同',length:years,year:1,annual:Array.from({length:years},(_,y)=>Number((salary*Math.pow(1.05,y)).toFixed(1)))} }).map(o=>({...o,total:Number(o.annual.reduce((a,b)=>a+b,0).toFixed(1))}))}
function grade(v){return v>=95?'超级巨星':v>=90?'联盟巨星':v>=85?'全明星':v>=80?'优质首发':v>=74?'首发级':v>=68?'轮换级':'潜力新秀'}
function calcOvr(attrs=state.attrs){if(!state.position)return 0;let sum=0,w=0;const weights=POS[state.position].weights;for(const [k] of ATTRS){if(attrs[k]!=null){sum+=attrs[k]*(weights[k]||.05);w+=(weights[k]||.05)}}return w?Math.round(sum/w):0}
function createPositionCards(){const g=$('#positionGrid');g.innerHTML='';Object.entries(POS).forEach(([k,p])=>{const b=document.createElement('button');b.className='pos-card';b.innerHTML=`<div class="pos-icon">${p.icon}</div><div class="pos-code">${k}</div><div class="pos-name">${p.name}</div><div class="pos-desc">${p.desc}</div>`;b.onclick=()=>{$$('.pos-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.position=k;$('#confirmPosition').disabled=false;save()};g.appendChild(b)})}
function initBuild(){state.attrs={};state.sources={};state.locked=0;state.rerolls=4;state.currentCandidates=[];state.ovr=0;renderBuild();newRound();show('build')}
function generatePlayer(attrKey){const sourcePos=Object.keys(POS)[rnd(0,4)];const base=rnd(66,96);const specialties={three:['PG','SG','SF'],pass:['PG','SF'],handle:['PG','SG'],rebound:['PF','C'],block:['PF','C'],strength:['PF','C'],perDef:['SG','SF','PF'],finish:['SG','SF','PF','C'],speed:['PG','SG','SF']};let raw=clamp(base+(specialties[attrKey]?.includes(sourcePos)?rnd(3,8):rnd(-5,3)),55,99);const target=state.position;let fit=sourcePos===target?1:0.94;if((target==='C'||target==='PF')&&(sourcePos==='PG'||sourcePos==='SG')&&['rebound','block','strength'].includes(attrKey))fit=.83;if((target==='PG'||target==='SG')&&(sourcePos==='C'||sourcePos==='PF')&&['handle','pass','speed'].includes(attrKey))fit=.84;if(['three','mid','durability'].includes(attrKey))fit=Math.max(fit,.94);const value=clamp(Math.round(raw*fit),50,99);const attrs={};ATTRS.forEach(([k])=>attrs[k]=clamp(raw+rnd(-14,12),45,99));attrs[attrKey]=value;return{name:NAMES[rnd(0,NAMES.length-1)],pos:sourcePos,team:TEAMS[rnd(0,TEAMS.length-1)][0],value,raw,fit,attrs}}
function currentAttr(){return ATTRS[state.locked]}
function newRound(){if(state.locked>=ATTRS.length)return reveal();const [key]=currentAttr();state.currentCandidates=[generatePlayer(key),generatePlayer(key),generatePlayer(key)];renderCandidates();save()}
function renderBuild(){if(!state.position)return;$('#buildPos').textContent=`位置 ${state.position}`;$('#lockedText').textContent=`${state.locked} / ${ATTRS.length}`;$('#buildProgress').style.width=`${state.locked/ATTRS.length*100}%`;const o=calcOvr();$('#liveOvr').textContent=state.locked?o:'--';$('#ovrRing').style.setProperty('--ovr',state.locked?o:0);$('#rerolls').textContent=state.rerolls;$('#rerollBtn').disabled=state.rerolls<=0;const list=$('#attrList');list.innerHTML='';ATTRS.forEach(([k,n],i)=>{const v=state.attrs[k];const row=document.createElement('div');row.className='attr-row '+(v==null?'pending':'');row.innerHTML=`<div><div class="name">${String(i+1).padStart(2,'0')} · ${n}</div><div class="source">${v!=null?state.sources[k].name+' · '+state.sources[k].pos:'等待锁定'}</div></div><strong>${v??'--'}</strong>`;list.appendChild(row)});if(state.locked<ATTRS.length){const [,n]=currentAttr();$('#attrTitle').textContent=`本轮目标：${n}`}}
function renderCandidates(){const [key,name]=currentAttr();$('#attrTitle').textContent=`本轮目标：${name}`;const g=$('#candidateGrid');g.innerHTML='';const max=Math.max(...state.currentCandidates.map(x=>x.value));state.currentCandidates.forEach((p,idx)=>{const c=document.createElement('article');c.className='candidate';const related=ATTRS.map(([k,n])=>[k,n,p.attrs[k]]).sort((a,b)=>b[2]-a[2]).slice(0,4);c.innerHTML=`<span class="tag">${p.pos} · 适配 ${Math.round(p.fit*100)}%</span><h4>${p.name}</h4><div class="team">${p.team} · 原始 ${p.raw}</div><div class="portrait">⛹️‍♂️</div><div class="cand-stats">${related.map(x=>`<div class="cand-stat">${x[1]}<b>${x[2]}</b></div>`).join('')}</div><button class="pick ${p.value===max?'best':''}">锁定 ${name} · ${p.value}</button>`;c.querySelector('.pick').onclick=()=>lockCandidate(idx,key);g.appendChild(c)})}
function lockCandidate(idx,key){const p=state.currentCandidates[idx];state.attrs[key]=p.value;state.sources[key]={name:p.name,pos:p.pos,team:p.team};state.locked++;state.ovr=calcOvr();renderBuild();toast(`${ATTRS.find(x=>x[0]===key)[1]} 已锁定：${p.value}`);setTimeout(newRound,180)}
function reveal(){state.ovr=calcOvr();state.potential=clamp(state.ovr+rnd(4,12),80,99);renderReveal();show('reveal')}
function archetype(){const a=state.attrs,p=state.position;const top=[['三分射手',a.three],['组织核心',a.pass+a.handle-80],['攻框机器',a.finish+a.speed-80],['防守大闸',a.perDef+a.steal-80],['护框支柱',a.block+a.rebound-80],['全能锋线',(a.finish+a.three+a.perDef+a.rebound)/2]];top.sort((x,y)=>y[1]-x[1]);return `${POS[p].name} · ${top[0][0]}`}
function renderReveal(){const o=state.ovr;$('#finalOvr').textContent=o;$('#finalGrade').textContent=grade(o).toUpperCase();$('#archetype').textContent=archetype();const best=ATTRS.map(([k,n])=>[n,state.attrs[k]]).sort((a,b)=>b[1]-a[1]).slice(0,7);$('#attributeCloud').innerHTML=best.map(x=>`<span class="pill">${x[0]} <b>${x[1]}</b></span>`).join('');$('#revealSummary').innerHTML=`<div class="summary-box"><b>${state.position}</b><span>位置</span></div><div class="summary-box"><b>${state.potential}</b><span>潜力</span></div><div class="summary-box"><b>${Math.round((state.attrs.durability||75)/10)}</b><span>耐久等级</span></div><div class="summary-box"><b>${state.rerolls}</b><span>剩余重抽</span></div>`}
function draft(){let base=state.ovr>=93?1:state.ovr>=89?rnd(1,4):state.ovr>=85?rnd(2,9):state.ovr>=80?rnd(6,18):rnd(12,30);state.pick=base;state.team=TEAMS[(base*7+rnd(0,TEAMS.length-1))%TEAMS.length];renderDraft();show('draft')}
function renderDraft(){const [team,emoji]=state.team;$('#teamBadge').textContent=emoji;$('#draftPick').innerHTML=`#${state.pick} <span>OVERALL PICK</span>`;$('#draftTeam').textContent=team;$('#draftReason').textContent=state.pick<=3?`球队认为你已经具备改变比赛的即战力，${state.ovr} 的初始总评和 ${state.potential} 的潜力让管理层愿意把建队方向交给你。`:`你在关键属性上的完成度打动了球队。相比单纯追求高 OVR，球队更看重你的 ${archetype().split('·')[1]} 特征与成长空间。`;const fits=[['位置需求',rnd(72,98)],['战术契合',rnd(70,96)],['即战能力',clamp(state.ovr,60,99)],['长期潜力',state.potential]];const rookie=makeRookieContract();$('#fitMeters').innerHTML=fits.map(x=>`<div class="meter"><div class="meter-head"><span>${x[0]}</span><b>${x[1]}</b></div><div class="meter-line"><i style="width:${x[1]}%"></i></div></div>`).join('')+`<div class="contract-card" style="margin-top:16px"><div class="contract-kicker">ROOKIE CONTRACT</div><div class="contract-main"><b>${money(rookie.annual[0])}</b><span>新秀年第1年年薪<br>${rookie.length}年总额 ${money(rookie.total)}</span></div><div class="contract-note">合同每个赛季都会记录当年工资；合同到期后将进入自由市场，由表现决定新报价。</div></div>`}
