(() => {
  const V5='V5';
  const TEAM_IDS={ATL:'1610612737',BOS:'1610612738',BKN:'1610612751',CHA:'1610612766',CHI:'1610612741',CLE:'1610612739',DAL:'1610612742',DEN:'1610612743',DET:'1610612765',GSW:'1610612744',HOU:'1610612745',IND:'1610612754',LAC:'1610612746',LAL:'1610612747',MEM:'1610612763',MIA:'1610612748',MIL:'1610612749',MIN:'1610612750',NOP:'1610612740',NYK:'1610612752',OKC:'1610612760',ORL:'1610612753',PHI:'1610612755',PHX:'1610612756',POR:'1610612757',SAC:'1610612758',SAS:'1610612759',TOR:'1610612761',UTA:'1610612762',WAS:'1610612764'};
  const logo=ab=>TEAM_IDS[ab]?`https://cdn.nba.com/logos/nba/${TEAM_IDS[ab]}/primary/L/logo.svg`:'';
  const totals=()=>({min:0,pts:0,reb:0,ast:0,stl:0,blk:0,to:0,fgm:0,fga:0,tpm:0,tpa:0,ftm:0,fta:0,gp:0});
  const avg=t=>{t=t||totals();const g=Math.max(1,t.gp);return{pts:t.pts/g,reb:t.reb/g,ast:t.ast/g,stl:t.stl/g,blk:t.blk/g,min:t.min/g,fg:t.fga?t.fgm/t.fga:0,tp:t.tpa?t.tpm/t.tpa:0,ft:t.fta?t.ftm/t.fta:0}};
  const ensure=()=>{if(!state||!state.name)return;state.playoffTotals=state.playoffTotals||totals();state.autoSim=false;state.autoResume=!!state.autoResume;if(state.playoffs){state.playoffs.history=state.playoffs.history||[];state.playoffs.completedSeries=state.playoffs.completedSeries||[];}for(const h of state.career||[]){h.totals=h.totals||null;h.playoffTotals=h.playoffTotals||null;h.playoffAvg=h.playoffAvg||avg(h.playoffTotals)}};

  document.title='NBA Career Lab V5';
  const brand=document.querySelector('.brand small');if(brand)brand.textContent='V5 · STAR LIFE SIMULATOR';
  const style=document.createElement('style');style.textContent=`
  .teammark img{width:46px;height:46px;object-fit:contain}.matchteam{display:grid;place-items:center;gap:5px}.matchlogo{width:46px;height:46px;object-fit:contain}.draftlogo{width:84px;height:84px;object-fit:contain;margin:8px auto}.attrpickgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:6px;margin-top:10px}.attrpick{display:flex;justify-content:space-between;align-items:center;gap:6px;border:1px solid #263649;background:#0b121b;color:#dce4ef;padding:8px 9px;border-radius:10px;font-size:10px;font-weight:800;cursor:pointer}.attrpick b{font-size:15px;color:#fff}.attrpick.best{border-color:#6f8530;background:#18220e;color:#eaff9d}.simcontrols{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin-top:12px}.decision{margin-top:10px;border:1px solid #70414a;background:#221217;border-radius:14px;padding:12px}.decision h4{margin:0 0 5px}.decision p{font-size:11px;color:#e5b9bf;line-height:1.6}.decision .actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.autobar{margin-top:8px;font-size:10px;color:var(--muted);text-align:center}.statgroup-title{font-size:12px;color:var(--accent);font-weight:900;letter-spacing:1px;margin:14px 0 8px}.careerhero{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:12px}.careerhero .mini b{font-size:20px}.seriesrow{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:10px;border:1px solid #253346;border-radius:12px;padding:9px;margin-top:7px}.seriesrow img{width:34px;height:34px;object-fit:contain}.seriesrow .score{font-size:18px;font-weight:950}.phasebadge{font-size:9px;color:var(--muted)}@media(max-width:580px){.simcontrols{grid-template-columns:1fr}.careerhero{grid-template-columns:1fr 1fr}.attrpickgrid{grid-template-columns:1fr 1fr}}`;
  document.head.appendChild(style);

  const buildDesc=document.querySelector('#build .section-head p');if(buildDesc)buildDesc.textContent='每一轮先随机一支球队。球队锁定后，从整队任意球员身上挑一项尚未占用的能力；高能力会排在前面，不再固定本轮属性。';
  const note=document.getElementById('rosterNote');if(note)note.textContent='抽到哪支球队，就使用该队完整阵容。每位球员会按剩余能力从高到低显示，直接点选要继承的那一项。';

  renderAttrList=function(){const g=$('#attrList');g.innerHTML='';ATTRS.forEach(([k,n],i)=>{const v=state.attrs[k],src=state.sources[k];g.insertAdjacentHTML('beforeend',`<div class="attrrow"><div><span>${String(i+1).padStart(2,'0')} · ${n}</span><br><small>${src?src.player+' · '+src.team:'等待选择'}</small></div><b>${v??'--'}</b></div>`)});$('#liveOvr').firstChild.nodeValue=state.buildIndex?calcOvr():'--';$('#buildBar').style.width=(state.buildIndex/ATTRS.length*100)+'%';$('#buildStep').textContent=`PICK ${Math.min(state.buildIndex+1,13)} / 13`;if(state.buildIndex<13)$('#roundTitle').textContent='本轮：自由选择剩余能力'};
  renderRoundTeam=function(){const ab=state.roundTeam;if(!ab){$('#teamMark').textContent='?';$('#teamName').textContent='点击随机球队开始本轮';$('#roster').innerHTML='';$('#randomTeamBtn').disabled=false;return}const t=DATA.teams[ab];$('#teamMark').innerHTML=`<img src="${logo(ab)}" alt="${ab}" onerror="this.parentElement.textContent='${ab}'">`;$('#teamName').textContent=t.name;const available=ATTRS.filter(([k])=>state.attrs[k]==null);const players=(t.players||[]).slice().sort((a,b)=>Math.max(...available.map(([k])=>playerRating(b,k)))-Math.max(...available.map(([k])=>playerRating(a,k))));$('#rosterNote').textContent=`${t.name} · 当前阵容 ${players.length} 人。每人按剩余能力从高到低排列；本轮只能继承一项，球队不能重抽。`;$('#roster').innerHTML='';players.forEach(p=>{const options=available.map(([k,n])=>({k,n,v:playerRating(p,k)})).sort((a,b)=>b.v-a.v);const card=document.createElement('article');card.className='player';const img=p.img?`<img src="${p.img}" alt="${p.name}" onerror="this.parentElement.innerHTML='<div class=\\'fallbackface\\'>${initials(p.name)}</div>'">`:`<div class="fallbackface">${initials(p.name)}</div>`;card.innerHTML=`<div class="photo">${img}</div><div class="player-body"><h4>${p.name}</h4><div class="meta">${p.pos||'NBA'} · ${ab}${p.salary?` · ${money(p.salary)}`:''}</div><div class="attrpickgrid">${options.map((o,i)=>`<button class="attrpick ${i<2&&o.v>=85?'best':''}" data-key="${o.k}"><span>${o.n}</span><b>${o.v}</b></button>`).join('')}</div></div>`;card.querySelectorAll('.attrpick').forEach(btn=>btn.onclick=()=>{const key=btn.dataset.key,label=ATTRS.find(x=>x[0]===key)?.[1]||key,v=playerRating(p,key);if(confirm(`继承 ${p.name} 的「${label}」 ${v}？`))chooseAttribute(p,key,v,ab)});$('#roster').appendChild(card)})};
  window.chooseAttribute=function(p,key,v,ab){if(state.attrs[key]!=null)return;state.attrs[key]=v;state.sources[key]={player:p.name,team:ab};state.buildIndex++;state.roundTeam=null;$('#randomTeamBtn').disabled=false;if(state.buildIndex>=ATTRS.length){state.ovr=calcOvr();state.potential=clamp(state.ovr+rnd(4,10),82,99);renderReveal();show('reveal')}else{renderAttrList();renderRoundTeam()}save()};

  const draftTitle=document.getElementById('draftTeam');if(draftTitle&&!document.getElementById('draftLogo'))draftTitle.insertAdjacentHTML('beforebegin','<img id="draftLogo" class="draftlogo" alt="team logo">');
  const oldRunDraft=runDraft;runDraft=function(){oldRunDraft();const el=$('#draftLogo');if(el)el.src=logo(state.team)};$('#draftBtn').onclick=runDraft;
  const next=$('#nextGame');if(next){const left=$('#yourTeam')?.parentElement,right=$('#oppTeam')?.parentElement;if(left&&!$('#yourTeamLogo')){left.classList.add('matchteam');$('#yourTeam').insertAdjacentHTML('beforebegin','<img id="yourTeamLogo" class="matchlogo" alt="">')}if(right&&!$('#oppTeamLogo')){right.classList.add('matchteam');$('#oppTeam').insertAdjacentHTML('beforebegin','<img id="oppTeamLogo" class="matchlogo" alt="">')}}

  const tabs=$('.tabs');if(tabs&&!$('[data-tab="playoffs"]')){
    tabs.innerHTML='<button class="btn tab active" data-tab="season">常规赛数据</button><button class="btn tab" data-tab="playoffs">季后赛数据</button><button class="btn tab" data-tab="careerstats">生涯数据</button><button class="btn tab" data-tab="games">比赛日志</button><button class="btn tab" data-tab="life">生活 / 商业</button><button class="btn tab" data-tab="national">国家队</button><button class="btn tab" data-tab="careerlog">生涯履历</button>';
    $('#tab-season').classList.add('active');$('#tab-games').classList.remove('active');
    $('#tab-season').insertAdjacentHTML('afterend','<div class="tabpane" id="tab-playoffs"><div class="panel gamebox"><div class="statgroup-title">NBA PLAYOFFS · BEST OF 7</div><div class="statline" id="playoffStats"></div><div id="seriesHistory"></div><div class="tablewrap"><table class="table"><thead><tr><th>轮次</th><th>G</th><th>对手</th><th>比分</th><th>MIN</th><th>PTS</th><th>REB</th><th>AST</th><th>STL</th><th>BLK</th><th>状态</th></tr></thead><tbody id="playoffLog"></tbody></table></div></div></div><div class="tabpane" id="tab-careerstats"><div class="panel gamebox"><div class="statgroup-title">NBA CAREER TOTALS</div><div class="careerhero" id="careerHeroStats"></div><div class="statline" id="careerStats"></div></div></div>');
    const h=$('#tab-season .panel');if(h&&!h.querySelector('.statgroup-title'))h.insertAdjacentHTML('afterbegin','<div class="statgroup-title">REGULAR SEASON</div>');
    const gh=$('#tab-games .panel');if(gh&&!gh.querySelector('.statgroup-title'))gh.insertAdjacentHTML('afterbegin','<div class="statgroup-title">REGULAR SEASON GAME LOG</div>');
    const head=$('#tab-careerlog thead tr');if(head)head.innerHTML='<th>赛季</th><th>年龄</th><th>球队</th><th>战绩</th><th>PTS</th><th>REB</th><th>AST</th><th>季后赛PTS</th><th>季后赛REB</th><th>季后赛AST</th><th>薪资</th><th>荣誉</th>';
  }
  const bindTabs=()=>$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tabpane').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#tab-'+b.dataset.tab)?.classList.add('active')});bindTabs();

  const pg=$('#playGameBtn');if(pg&&!$('#autoSeasonBtn'))pg.outerHTML='<div class="simcontrols"><button class="btn primary" id="playGameBtn">模拟下一场</button><button class="btn blue" id="autoSeasonBtn">自动模拟本赛季</button><button class="btn" id="restGameBtn">轮休下一场</button></div><div class="autobar" id="autoStatus">逐场模拟 · 自动模式遇到伤病会暂停</div><div id="injuryDecision"></div>';
  let autoTimer=null;
  const v4Line=simulatePlayerLine;
  simulatePlayerLine=function(mult=1){const l=v4Line();if(mult>=.999)return l;for(const k of ['min','pts','reb','ast','stl','blk','fgm','fga','tpm','tpa','ftm','fta'])l[k]=Math.max(0,Math.round((l[k]||0)*mult));l.fgm=Math.min(l.fgm,l.fga);l.tpm=Math.min(l.tpm,l.tpa);l.ftm=Math.min(l.ftm,l.fta);return l};
  window.addTotalsTo=(t,l)=>{t.gp++;for(const k of ['min','pts','reb','ast','stl','blk','to','fgm','fga','tpm','tpa','ftm','fta'])t[k]+=l[k]||0};
  const recoverOne=()=>{if(state.injury){state.injury.games--;if(state.injury.games<=0){state.news.unshift(`${state.name} 已从 ${state.injury.name} 中恢复。`);state.injury=null}}if(state.illness){state.illness.games--;if(state.illness.games<=0){state.news.unshift(`${state.name} 已恢复健康。`);state.illness=null}}state.fatigue=clamp(state.fatigue-rnd(5,10),0,100);state.health=clamp(state.health+rnd(1,4),0,100)};
  const worsen=()=>{if(state.injury&&Math.random()<.22){const extra=rnd(2,8);state.injury.games+=extra;state.news.unshift(`带伤出战导致 ${state.injury.name} 恢复期延长 ${extra} 场。`);state.health=clamp(state.health-rnd(4,10),20,100)}};
  window.stopAuto=function(keepResume=false){state.autoSim=false;clearTimeout(autoTimer);autoTimer=null;if(!keepResume)state.autoResume=false;if($('#autoSeasonBtn'))$('#autoSeasonBtn').textContent='自动模拟本赛季';if($('#autoStatus'))$('#autoStatus').textContent='逐场模拟 · 自动模式遇到伤病会暂停';save()};
  const scheduleAuto=()=>{clearTimeout(autoTimer);autoTimer=setTimeout(()=>{if(state.autoSim)simulateRegularGame('normal')},220)};
  window.startAuto=function(){ensure();if(state.phase!=='regular'||state.offseason||state.gameIndex>=82)return;if(state.injury||state.illness){state.autoResume=true;renderCareer();return}state.autoSim=true;$('#autoSeasonBtn').textContent='暂停自动模拟';$('#autoStatus').textContent=`自动模拟中 · ${state.gameIndex}/82`;scheduleAuto();save()};
  window.toggleAuto=()=>state.autoSim?stopAuto():startAuto();
  simulateRegularGame=function(mode='normal'){ensure();if(state.gameIndex>=82){stopAuto();finishRegular();return}const g=state.schedule[state.gameIndex],hurt=state.injury||state.illness;if(hurt&&mode==='normal'){stopAuto(true);state.autoResume=true;renderCareer();return}let active=true,status='Played',line=null;if(mode==='rest'){active=false;status=hurt?`DNP · 养伤 ${hurt.name}`:'DNP · Load Management';recoverOne()}else if(hurt&&mode==='playThrough'){line=simulatePlayerLine(.78);status=`Played through · ${hurt.name}`;addTotals(line);state.fatigue=clamp(state.fatigue+rnd(7,13),0,100);worsen()}else{line=simulatePlayerLine();addTotals(line)}const [us,them]=simulateScore(teamPower(state.team),teamPower(g.opp),active),win=us>them;if(win)state.wins++;else state.losses++;state.gameIndex++;if(active&&mode!=='playThrough')state.fatigue=clamp(state.fatigue+rnd(2,6),0,100);if(active&&mode!=='playThrough'){injuryRoll();state.fame=clamp(state.fame+(line.pts>=35?.7:line.pts>=25?.3:.05)+(win?.08:0),0,100);state.followers+=line.pts>=30?.015:.003}state.gameLog.unshift({n:state.gameIndex,opp:g.opp,home:g.home,us,them,win,status,line});state.gameLog=state.gameLog.slice(0,120);if(state.gameIndex===50)allStarCheck();renderCareer();save();if(state.gameIndex>=82){stopAuto();setTimeout(finishRegular,150);return}if(state.autoSim){if(state.injury||state.illness){state.autoResume=true;stopAuto(true);renderCareer()}else scheduleAuto()}};
  window.restNextGame=()=>{if(state.phase==='regular'&&!state.offseason)simulateRegularGame('rest')};
  window.playThroughNextGame=()=>{const resume=state.autoResume;state.autoResume=false;simulateRegularGame('playThrough');if(resume&&!state.injury&&!state.illness&&state.phase==='regular'&&!state.offseason)startAuto()};
  window.healNextGame=()=>{const resume=state.autoResume;state.autoResume=false;simulateRegularGame('rest');if(resume&&!state.injury&&!state.illness&&state.phase==='regular'&&!state.offseason)startAuto()};

  window.playoffAverages=()=>avg(state.playoffTotals||totals());
  finishRegular=function(){ensure();if(state.phase!=='regular')return;stopAuto();const a=currentAverages();if(a.pts>=27&&state.wins>=50){state.awards.push('MVP');state.fame+=10}if(a.pts>=23)state.awards.push('All-NBA');if((state.attrs.defense||0)>=88&&(state.attrs.steal||0)>=82)state.awards.push('All-Defense');state.phase='playoffs';state.playoffTotals=totals();if(state.wins<38){state.playoffs={eliminated:true,round:'Missed Playoffs',history:[],completedSeries:[]};startOffseason();return}const opp=one(TEAM_KEYS.filter(x=>x!==state.team));state.playoffs={roundIndex:0,rounds:['First Round','Conference Semifinals','Conference Finals','NBA Finals'],opp,w:0,l:0,history:[],completedSeries:[],eliminated:false,champion:false};state.news.unshift(`季后赛开始：首轮对手 ${DATA.teams[opp].name}。`);renderCareer();save()};
  simulatePlayoffGame=function(mode='normal'){ensure();const p=state.playoffs;if(!p||p.eliminated||p.champion)return;const hurt=state.injury||state.illness;if(hurt&&mode==='normal'){renderCareer();return}let active=true,line=null,status='Played';if(mode==='rest'){active=false;status=hurt?`DNP · 养伤 ${hurt.name}`:'DNP · Rest';recoverOne()}else if(hurt&&mode==='playThrough'){line=simulatePlayerLine(.8);status=`Played through · ${hurt.name}`;addTotalsTo(state.playoffTotals,line);worsen()}else{line=simulatePlayerLine();addTotalsTo(state.playoffTotals,line);injuryRoll()}const [us,them]=simulateScore(teamPower(state.team)+3,teamPower(p.opp)+3,active),win=us>them;if(win)p.w++;else p.l++;const round=p.rounds[p.roundIndex],gameNo=p.history.filter(x=>x.round===round).length+1;p.history.unshift({round,gameNo,opp:p.opp,us,them,win,line,status});if(p.w===4||p.l===4){p.completedSeries.push({round,opp:p.opp,w:p.w,l:p.l});if(p.w===4){if(p.roundIndex===3){p.champion=true;state.awards.push('NBA Champion');state.fame+=15;state.news.unshift(`${state.name} 赢得 NBA 总冠军！`);if(playoffAverages().pts>=22){state.awards.push('Finals MVP');state.fame+=8}renderCareer();save();startOffseason();return}p.roundIndex++;p.w=0;p.l=0;p.opp=one(TEAM_KEYS.filter(x=>x!==state.team));state.news.unshift(`晋级 ${p.rounds[p.roundIndex]}，对手 ${DATA.teams[p.opp].name}。`)}else{p.eliminated=true;state.news.unshift(`${state.name} 的季后赛之旅在 ${round} 结束。`);renderCareer();save();startOffseason();return}}renderCareer();save()};
  window.playoffRest=()=>simulatePlayoffGame('rest');window.playoffPlayThrough=()=>simulatePlayoffGame('playThrough');

  startOffseason=function(){ensure();if(state.offseason)return;state.offseason=true;state.offseasonActions=3;const a=currentAverages(),pa=playoffAverages();state.career.push({season:seasonLabel(state.seasonYear),age:state.age,team:state.team,record:`${state.wins}-${state.losses}`,avg:a,totals:{...state.seasonTotals},playoffAvg:pa,playoffTotals:{...state.playoffTotals},salary:currentSalary(),awards:[...state.awards]});state.allAwards.push(...state.awards.map(x=>`${seasonLabel(state.seasonYear)} ${x}`));state.careerEarnings+=currentSalary();state.netWorth+=currentSalary()*.48+state.endorsements.reduce((s,e)=>s+e.annual,0)*.65;state.awards=[];const n=nationalEventForYear(state.seasonYear);if(n)state.pendingNational=n;generateEndorsementOffers();renderCareer();save()};
  finishOffseason=function(){ensure();if(!state.offseason)return;if(state.pendingNational)return alert('先处理国家队邀请。');if(state.offseasonActions>0&&!confirm(`还有 ${state.offseasonActions} 个休赛期活动名额没用，确定直接进入下一季？`))return;state.endorsements=state.endorsements.map(e=>({...e,remaining:e.remaining-1})).filter(e=>e.remaining>0);state.businesses=state.businesses.map(b=>({...b,value:+(b.value*(.92+Math.random()*.22)).toFixed(1)}));state.netWorth+=state.businesses.reduce((s,b)=>s+b.value*.04,0);if(state.contract){if(state.contract.year>=state.contract.years)state.contract=salaryOffer();else state.contract.year++}state.age++;state.seasonNo++;state.seasonYear++;if(state.age>=44||(state.age>=42&&state.ovr<78)){retire('身体和联盟评估共同决定职业生涯结束。');return}if(state.age>=35){const decline=state.age>=40?rnd(2,5):rnd(0,3);state.ovr=clamp(state.ovr-decline,62,99)}else if(state.age<=27&&state.ovr<state.potential)state.ovr=clamp(state.ovr+rnd(0,2),62,state.potential);state.fatigue=clamp(state.fatigue-35,0,100);state.health=clamp(state.health+rnd(2,8),35,100);state.injury=null;state.illness=null;state.offseason=false;state.wins=0;state.losses=0;state.gameLog=[];state.seasonTotals=totals();state.playoffTotals=totals();state.autoSim=false;state.autoResume=false;state.phase='regular';state.playoffs=null;addFutureRookies();createSchedule();renderCareer();save()};

  renderLastGame=function(){let g=null,phase='REGULAR';if(state.phase==='playoffs'&&state.playoffs?.history?.length){g=state.playoffs.history[0];phase='PLAYOFFS'}else g=state.gameLog[0];if(!g){$('#lastGameBox').innerHTML='';return}const l=g.line;$('#lastGameBox').innerHTML=`<div class="scorecard"><div class="scoreline"><div><b>${g.us}</b><div class="muted">${state.team}</div></div><div style="text-align:center"><div class="kicker">${phase} · ${g.win?'WIN':'LOSS'}</div><div class="muted">vs ${g.opp}</div></div><div style="text-align:right"><b>${g.them}</b><div class="muted">${g.opp}</div></div></div>${l?`<div class="statline">${[['MIN',l.min],['PTS',l.pts],['REB',l.reb],['AST',l.ast],['STL',l.stl],['BLK',l.blk]].map(x=>`<div class="sbox"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}</div>`:`<div class="injury" style="margin-top:12px">${g.status||'DNP'}</div>`}</div>`};
  renderPlayoffs=function(){const p=state.playoffs;if(!p){$('#playoffBox').innerHTML='';return}if(p.eliminated&&p.round==='Missed Playoffs'){$('#playoffBox').innerHTML='<div class="playoff"><div class="series">Missed Playoffs</div></div>';return}const current=p.champion?'NBA CHAMPION':p.eliminated?'SEASON COMPLETE':`${p.rounds[p.roundIndex]} · ${state.team} ${p.w} – ${p.l} ${p.opp}`;$('#playoffBox').innerHTML=`<div class="playoff"><div class="kicker">BEST OF 7 · FIRST TO 4</div><div class="series">${current}</div><div class="muted">每轮严格七场四胜；常规赛与季后赛数据分开统计。</div></div>`};
  const statBoxes=t=>{const a=avg(t);return[['GP',t.gp],['PTS',a.pts.toFixed(1)],['REB',a.reb.toFixed(1)],['AST',a.ast.toFixed(1)],['STL',a.stl.toFixed(1)],['BLK',a.blk.toFixed(1)],['FG%',(a.fg*100).toFixed(1)],['3P%',(a.tp*100).toFixed(1)],['FT%',(a.ft*100).toFixed(1)]]};
  renderSeason=function(){ensure();$('#seasonStats').innerHTML=statBoxes(state.seasonTotals).map(x=>`<div class="sbox"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');$('#awards').innerHTML=(state.awards.length?state.awards:['暂无荣誉']).map(x=>`<span class="chip">${x}</span>`).join('');$('#leagueNews').innerHTML=state.news.slice(0,12).map(x=>`<div class="feeditem">${x}</div>`).join('')};
  window.renderPlayoffStats=function(){ensure();if(!$('#playoffStats'))return;const t=state.playoffTotals||totals();$('#playoffStats').innerHTML=statBoxes(t).map(x=>`<div class="sbox"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');const p=state.playoffs,h=p?.history||[];$('#playoffLog').innerHTML=h.map(g=>{const l=g.line;return`<tr><td>${g.round}</td><td>G${g.gameNo||''}</td><td>${g.opp}</td><td>${g.us}-${g.them}</td><td>${l?.min??'—'}</td><td>${l?.pts??'—'}</td><td>${l?.reb??'—'}</td><td>${l?.ast??'—'}</td><td>${l?.stl??'—'}</td><td>${l?.blk??'—'}</td><td>${g.status||'Played'}</td></tr>`}).join('');$('#seriesHistory').innerHTML=(p?.completedSeries||[]).map(x=>`<div class="seriesrow"><img src="${logo(x.opp)}" alt=""><div><div class="phasebadge">${x.round}</div><b>${DATA.teams[x.opp]?.name||x.opp}</b></div><div class="score">${x.w}-${x.l}</div></div>`).join('')};
  const aggregate=()=>{const rs=totals(),po=totals();for(const h of state.career||[]){for(const k in rs)rs[k]+=h.totals?.[k]||0;for(const k in po)po[k]+=h.playoffTotals?.[k]||0}if(!state.offseason){for(const k in rs)rs[k]+=state.seasonTotals?.[k]||0;for(const k in po)po[k]+=state.playoffTotals?.[k]||0}return{rs,po}};
  window.renderCareerStats=function(){ensure();if(!$('#careerStats'))return;const {rs,po}=aggregate(),a=avg(rs),pa=avg(po),seasons=(state.career||[]).length+(state.offseason?0:1),rings=(state.allAwards||[]).filter(x=>x.includes('NBA Champion')).length+(state.awards||[]).filter(x=>x==='NBA Champion').length,mvps=(state.allAwards||[]).filter(x=>x.endsWith(' MVP')).length+(state.awards||[]).filter(x=>x==='MVP').length;$('#careerHeroStats').innerHTML=`<div class="mini"><span>NBA赛季</span><b>${seasons}</b></div><div class="mini"><span>常规赛总场次</span><b>${rs.gp}</b></div><div class="mini"><span>总冠军</span><b>${rings}</b></div><div class="mini"><span>MVP</span><b>${mvps}</b></div>`;const rows=[['总得分',Math.round(rs.pts)],['总篮板',Math.round(rs.reb)],['总助攻',Math.round(rs.ast)],['常规赛场均',`${a.pts.toFixed(1)} / ${a.reb.toFixed(1)} / ${a.ast.toFixed(1)}`],['季后赛场次',po.gp],['季后赛总得分',Math.round(po.pts)],['季后赛场均',`${pa.pts.toFixed(1)} / ${pa.reb.toFixed(1)} / ${pa.ast.toFixed(1)}`],['生涯工资',money(state.careerEarnings+(state.offseason?0:currentSalary()))],['国家队出场',state.national?.caps||0]];$('#careerStats').innerHTML=rows.map(x=>`<div class="sbox"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')};
  renderCareerLog=function(){$('#careerLog').innerHTML=(state.career||[]).map(h=>`<tr><td>${h.season}</td><td>${h.age}</td><td>${h.team}</td><td>${h.record}</td><td>${h.avg.pts.toFixed(1)}</td><td>${h.avg.reb.toFixed(1)}</td><td>${h.avg.ast.toFixed(1)}</td><td>${(h.playoffAvg?.pts||0).toFixed(1)}</td><td>${(h.playoffAvg?.reb||0).toFixed(1)}</td><td>${(h.playoffAvg?.ast||0).toFixed(1)}</td><td>${money(h.salary)}</td><td>${h.awards.join(' / ')||'—'}</td></tr>`).join('')};

  const oldRenderCareer=renderCareer;
  renderCareer=function(){ensure();oldRenderCareer();ensure();$('#yourTeamLogo')&&($('#yourTeamLogo').src=logo(state.team));const decision=$('#injuryDecision');if(decision)decision.innerHTML='';const auto=$('#autoSeasonBtn'),rest=$('#restGameBtn'),play=$('#playGameBtn');if(state.phase==='regular'&&!state.offseason){const g=state.schedule[state.gameIndex];if($('#oppTeamLogo'))$('#oppTeamLogo').src=g?logo(g.opp):'';if(play){play.textContent='模拟下一场';play.disabled=!g||!!(state.injury||state.illness);play.onclick=()=>simulateRegularGame('normal')}if(auto){auto.style.display='';auto.disabled=!g;auto.textContent=state.autoSim?'暂停自动模拟':'自动模拟本赛季';auto.onclick=toggleAuto}if(rest){rest.style.display='';rest.textContent=(state.injury||state.illness)?'休息 / 养伤一场':'轮休下一场';rest.onclick=restNextGame}if(state.injury||state.illness){const h=state.injury||state.illness;decision.innerHTML=`<div class="decision"><h4>${state.injury?'伤病决策':'健康决策'} · ${h.name}</h4><p>休息会推进恢复；带伤/带病出战会降低本场表现，并有加重伤势的风险。自动模拟已暂停。</p><div class="actions"><button class="btn" onclick="healNextGame()">休息养伤</button><button class="btn danger" onclick="playThroughNextGame()">带伤出战</button></div></div>`}}else if(state.phase==='playoffs'&&!state.offseason){if($('#oppTeamLogo'))$('#oppTeamLogo').src=state.playoffs?.opp?logo(state.playoffs.opp):'';if(play){play.textContent='模拟下一场季后赛';play.disabled=state.playoffs?.eliminated||state.playoffs?.champion||!!(state.injury||state.illness);play.onclick=()=>simulatePlayoffGame('normal')}if(auto)auto.style.display='none';if(rest){rest.style.display='';rest.textContent=(state.injury||state.illness)?'季后赛休战一场':'主动轮休季后赛';rest.onclick=playoffRest}if(state.injury||state.illness){const h=state.injury||state.illness;decision.innerHTML=`<div class="decision"><h4>季后赛伤病决策 · ${h.name}</h4><p>七场四胜。可以休战一场养伤，也可以带伤出战，承担表现下降和伤势恶化风险。</p><div class="actions"><button class="btn" onclick="playoffRest()">休战养伤</button><button class="btn danger" onclick="playoffPlayThrough()">带伤出战</button></div></div>`}}else{if($('#oppTeamLogo'))$('#oppTeamLogo').src='';if(auto)auto.style.display='none';if(rest)rest.style.display='none'}renderPlayoffStats();renderCareerStats();renderCareerLog()};

  const v4Create=createState;createState=function(){const s=v4Create();s.playoffTotals=totals();s.autoSim=false;s.autoResume=false;return s};
  if(state?.name)ensure();
  if($('#continueBtn')&&localStorage.getItem(SAVE))$('#continueBtn').textContent='继续已有生涯 · V5兼容存档';
  console.info('[NBA Career Lab] V5 enhancement loaded');
})();
